
name: CI

on:
   push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

   Jobs:
  
  build: 
    
    runs-on: ubuntu-latest
     steps:
          - uses: actions/checkout@v4
           - name: Build image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/portfolio .
      
      - name: Push image
        run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.REGISTRY_PASS}}
        docker push ${{secrets.DOCKER_USERNAME}}/portfolio
          
